jasypt:
  encryptor:
    password: ${jasyptpwd:mi-adn-secreto}
    algorithm: PBEWithMD5AndDES

server:
  allowedOrigins: http://localhost:4200
  port: 8084
  servlet:
    context-path: /alquiler-motos
    session:
      timeout: 21600s

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    jdbcUrl: jdbc:mysql://localhost:3306/alquiler-motos?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: adn
    password: ENC(NeBzn0lkscD59IhfSdBmuw==)
    hikari:
      poolName: pool
